In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("/worker_health_dataset.xlsx")
df.head()

,worker_id,age,department,shift_duration_hrs,reported_symptoms,diagnosis,ppe_compliance_score,audio_alert_flag,risk_level,outcome
0,W1000,48,Paint Shop,7.4,minor knee pain after long standing shift,Dehydration (mild),0.79,0,LOW,First Aid
1,W1001,51,Boiler Room,6.2,"occasional dizziness, light sensitivity",Dehydration (mild),0.73,0,LOW,Rest and Resume
2,W1002,31,Assembly Line,8.7,"muscle soreness, mild back ache",Mild Allergic Reaction,0.94,0,LOW,First Aid
3,W1003,58,Heavy Machinery,8.8,minor knee pain after long standing shift,Mild Allergic Reaction,0.91,0,LOW,No Treatment Required
4,W1004,54,Boiler Room,12.2,"heat stroke symptoms, no sweating, skin hot an...",Heat Stroke,0.33,1,HIGH,ICU Admission

In [ ]:
print(df.shape)

In [ ]:
df = df.drop(["worker_id","reported_symptoms","diagnosis","outcome"],axis = 1)
df.head()

In [ ]:
df = pd.get_dummies(df,columns=["department","risk_level"], drop_first = True)
df.head()

In [ ]:
X = df.drop("ppe_compliance_score", axis=1)
y = df["ppe_compliance_score"]

print(X.shape)
print(y.shape)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape, X_test.shape)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

In [ ]:
y_pred = model.predict(X_test)

print(y_pred[:5])

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2 Score:", r2)

In [ ]:
model.coef_

In [ ]:
model.intercept_

VISUALIZATION

In [ ]:
import matplotlib.pyplot as plt

plt.scatter(y_test, y_pred)
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual vs Predicted")
plt.show()

SAVE MODEL USING PICKLE

In [ ]:
import pickle

In [ ]:
with open('zentrix_pkl','wb') as file:
  pickle.dump(model,file)

LOADING THE SAVED MODEL

In [ ]:
with open('zentrix_pkl','rb') as file:
  zp = pickle.load(file)

In [ ]:
zp.coef_

In [ ]:
zp.intercept_

In [ ]:
zp.predict(X_test)

**SAVE TRAINED MODEL USING JOBLIB**

In [ ]:
import joblib

In [ ]:
joblib.dump(model,'zentrix_joblib')

**LOAD SAVED MODEL**

In [ ]:
mj = joblib.load('zentrix_joblib')

In [ ]:
mj.coef_

In [ ]:
mj.intercept_

In [ ]:
mj.predict(X_test)

**PERFORMING ONE-HOT ENCODING**

In [42]:
print(df.columns)

Index(['age', 'shift_duration_hrs', 'ppe_compliance_score', 'audio_alert_flag',
       'department_Boiler Room', 'department_Chemical Processing',
       'department_Electrical Unit', 'department_Foundry',
       'department_Heavy Machinery', 'department_Mining Section',
       'department_Paint Shop', 'department_Warehouse',
       'department_Welding Unit', 'risk_level_LOW', 'risk_level_MEDIUM'],
      dtype='object')

In [44]:
cols_to_drop = ["worker_id", "reported_symptoms"]
df = df.drop(columns=[col for col in cols_to_drop if col in df.columns])

In [45]:
categorical_cols = df.select_dtypes(include=["object"]).columns

In [49]:
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True).astype(int)
df_encoded.head()

,age,shift_duration_hrs,ppe_compliance_score,audio_alert_flag,department_Boiler Room,department_Chemical Processing,department_Electrical Unit,department_Foundry,department_Heavy Machinery,department_Mining Section,department_Paint Shop,department_Warehouse,department_Welding Unit,risk_level_LOW,risk_level_MEDIUM
0,48,7,0,0,0,0,0,0,0,0,1,0,0,1,0
1,51,6,0,0,1,0,0,0,0,0,0,0,0,1,0
2,31,8,0,0,0,0,0,0,0,0,0,0,0,1,0
3,58,8,0,0,0,0,0,0,1,0,0,0,0,1,0
4,54,12,0,1,1,0,0,0,0,0,0,0,0,0,0

In [50]:
df_encoded.shape

(1000, 15)

**PERFORMING TRAIN TEST SPLIT**

In [55]:
X = df.drop(columns=["risk_level_LOW", "risk_level_MEDIUM"])

y = (df["risk_level_LOW"] == 0) & (df["risk_level_MEDIUM"] == 0)
y = y.astype(int)

In [57]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3,random_state=10)
print(X_train.shape, X_test.shape)

(700, 13) (300, 13)

**LINEAR** **REGRESSION**

In [58]:
from sklearn.linear_model import LinearRegression
f = LinearRegression()
f.fit(X_train, y_train)

LinearRegression()

In [59]:
f.predict(X_test)

array([ 5.37896972e-01, -9.19586140e-02,  3.46880556e-01,  3.14675942e-01,
        2.94350456e-01,  3.51242973e-01,  4.27455910e-01,  8.45015965e-01,
       -7.84490580e-02, -2.02361171e-01,  2.78223706e-01,  7.96458372e-02,
        6.41930989e-01, -1.72228319e-01,  3.64848419e-01,  2.76659377e-01,
       -6.36857722e-02, -1.70942675e-01,  1.84876600e-01,  9.32864458e-01,
        6.48756199e-01,  2.56555813e-01, -8.11645142e-02, -6.49786663e-02,
       -1.12152787e-01, -1.70907713e-01,  8.42339836e-01, -7.74349660e-02,
        2.69245920e-01,  3.55388560e-01,  6.71718325e-01,  2.76582449e-01,
        3.29474609e-01, -1.36750903e-01, -2.11653876e-01,  6.04092460e-01,
       -1.87059723e-01,  2.31974062e-01,  1.34799564e-01, -9.20641664e-03,
       -8.32417770e-02, -1.78025737e-01,  2.14618226e-01,  8.59851505e-02,
       -1.56340265e-01, -1.28870633e-01, -3.71310085e-02, -1.02890671e-01,
       -1.39170282e-01,  3.86613245e-01, -1.13635701e-01,  4.72677522e-01,
       -2.17376627e-01, -2.69791615e-02,  2.55085693e-01, -3.01738832e-02,
       -2.03003718e-01,  2.56255135e-01,  1.95839946e-01,  3.38670677e-01,
        4.50955556e-01,  2.63359286e-01, -1.48867771e-01,  8.55328247e-01,
        1.30810518e-01, -1.00581643e-01,  4.18473726e-01, -1.43877388e-01,
        2.57655484e-01,  1.75845841e-01,  8.47418664e-01, -6.77370940e-02,
       -2.40109851e-01,  4.90187716e-01,  8.88878398e-01,  5.83038725e-01,
       -1.00038929e-01,  3.25061879e-01,  2.40366048e-01,  8.41285123e-01,
        4.29517518e-01,  2.41158220e-01, -1.20771840e-01,  3.32273806e-01,
       -8.74748303e-04,  2.81364967e-01,  3.67381547e-02, -1.54545442e-01,
        8.49743653e-02,  6.65676772e-02, -1.45092740e-01,  3.28659194e-01,
       -1.39484851e-01,  8.75223496e-03,  1.95862510e-01,  3.44312785e-01,
       -1.47688268e-01, -1.50451740e-01,  1.39808941e-01,  2.92542377e-01,
       -1.58529305e-01,  7.07089533e-01,  2.60088102e-02, -1.13669845e-01,
       -4.01606666e-02,  1.26632036e-01,  1.32667049e-01, -4.33288008e-02,
        3.07725860e-01, -3.68169855e-03,  8.10547531e-01,  1.71402194e-01,
       -3.16277098e-02, -1.26429467e-02, -2.68278891e-01, -4.41288609e-02,
        3.37954273e-01,  2.89394128e-01,  8.42134628e-02,  2.09240955e-01,
        1.86571830e-01,  6.95206754e-01,  1.71669137e-01,  7.93476850e-01,
        8.99075102e-02, -8.14131340e-02,  1.41637939e-01,  6.03543139e-01,
        5.58636769e-02, -1.39023294e-01, -6.47655546e-03,  3.77413386e-01,
       -1.20920488e-01,  5.58444781e-01,  1.86512648e-01,  9.73861538e-03,
        2.36428340e-04,  1.63110189e-01, -2.17175110e-01,  1.69633862e-01,
        8.18723237e-01, -9.05576778e-02,  4.27961695e-01, -5.32738920e-02,
       -7.32363967e-02,  6.88146946e-01,  4.36056201e-01,  1.07459265e-01,
       -1.49210794e-01,  4.06686615e-01, -4.95204574e-02, -1.43370077e-02,
        2.06184131e-01, -2.31442424e-01, -1.81182432e-01,  1.81269385e-01,
       -4.76904322e-02,  4.52570400e-01, -1.34243054e-01,  6.74048324e-01,
       -1.43370077e-02, -1.27334248e-01,  3.19658956e-01, -9.13590104e-02,
        5.59112280e-01,  4.16406737e-01,  7.30883308e-02, -6.93623614e-02,
        2.76848970e-02, -1.39799815e-01,  1.92170796e-01,  2.27152468e-02,
        8.87373909e-01,  9.81493332e-02, -7.30954904e-02, -1.03107996e-01,
        2.04978310e-01, -1.19747887e-01,  7.88109020e-01,  7.21139635e-01,
        2.68582298e-01,  5.40295008e-01,  8.04586093e-01,  4.68241688e-02,
        1.91119800e-02,  7.77843497e-01, -3.38774232e-03,  6.79041709e-01,
       -1.56869146e-01,  5.74981243e-01, -1.36188780e-01,  2.27566140e-01,
        7.88395544e-01, -9.26528774e-02, -7.62103468e-02,  2.70159897e-01,
        4.33485506e-02,  3.93047582e-02,  3.28116820e-01, -6.13298504e-02,
        1.55169321e-01,  2.27397172e-01,  6.52575482e-01,  1.10562702e-01,
       -4.63901351e-02,  5.86547930e-01,  3.89933181e-01,  4.99954664e-01,
        1.96190178e-01,  3.51113278e-01, -4.33862418e-03,  4.88537818e-01,
        3.93483037e-01,  1.67522931e-01,  7.05956420e-01, -4.59433573e-02,
        2.70595559e-01,  7.56165028e-01,  1.41666490e-01, -7.43245869e-02,
       -7.53817016e-02,  2.83232098e-01,  2.03890830e-02,  1.18916745e-02,
       -2.31577469e-01, -4.12069862e-02,  5.73233219e-01,  2.61688446e-01,
       -4.62352515e-02,  5.66034828e-02, -2.43487049e-01,  5.25258008e-02,
        5.09675262e-01, -1.21736839e-01,  3.62875086e-01,  1.05847841e-01,
        7.24375018e-02, -3.02857294e-01,  2.77156913e-01,  8.26004674e-01,
       -1.09683200e-01,  5.27458928e-01,  6.98487488e-01,  2.46731033e-01,
       -5.24569846e-02, -9.98458433e-02, -1.43205046e-01, -3.87445910e-02,
        2.39254927e-01,  6.37835679e-01,  9.83403178e-03, -3.89099024e-02,
       -8.73843486e-02,  1.43831304e-01,  1.29152614e-02,  2.86801490e-01,
        1.34081323e-01, -1.64051106e-01,  1.80368022e-02,  2.08031677e-01,
        2.13153289e-01, -5.70007651e-02,  2.86794461e-01,  3.51722945e-01,
       -1.79761700e-01, -2.98727581e-02, -1.30620661e-02, -2.99473863e-01,
       -1.11025855e-01, -1.40112015e-01,  2.23758007e-02, -2.06437064e-01,
        1.13120355e-03,  4.93308533e-02, -1.72587287e-01,  3.07344035e-01,
        1.57801194e-01, -4.83892720e-02, -9.89961747e-05,  2.23823295e-01,
       -5.42582507e-03, -1.37541603e-01,  3.19216101e-01,  2.32685312e-01,
       -1.08740804e-01, -1.27839768e-01,  3.56889927e-01, -1.14871268e-01,
        1.64785721e-02, -1.20884031e-01, -3.36280195e-02,  6.57894110e-01,
       -1.48481007e-01,  1.60726992e-01,  2.14937108e-01, -2.24637972e-02,
       -2.04705677e-01, -8.97388882e-02,  3.26389706e-01, -1.36397093e-01])

In [60]:
f.score(X_test,y_test)

0.5840128343846525

**LOGISTIC REGRESSION**

In [62]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

print("Accuracy:", model.score(X_test, y_test))

Accuracy: 0.9833333333333333